### ISSUE TITLE
Gene annotation fails on large run

### ISSUE THREAD

**Issue by danvk** [hammerlab/cycledash#494]
See http://cycledash.demeter.hpc.mssm.edu/runs/232/examine

**Comment by danvk** [comment]
on the other hand, it worked on this even larger one: http://cycledash.demeter.hpc.mssm.edu/runs/156/examine

**Comment by danvk** [comment]
Here are the only relevant worker logs I see from run 232:

```
[2015-02-25 19:09:36,070: WARNING/MainProcess] celery@worker.1 ready.
[2015-02-25 19:09:36,072: WARNING/MainProcess] celery@worker.3 ready.
[2015-02-25 19:09:36,080: WARNING/MainProcess] celery@worker.2 ready.
[2015-02-25 19:09:38,099: ERROR/MainProcess] Task workers.gene_annotator.annotate[d6ef49cd-5f25-4520-b18d-6ad1e5764372] raised unexpected: WorkerLostError('Worker exited prematurely: signal -15.',)
Traceback (most recent call last):
  File "/home/cycledash/cycledash/venv/lib/python2.7/site-packages/billiard/pool.py", line 1170, in mark_as_worker_lost
    human_status(exitcode)),
WorkerLostError: Worker exited prematurely: signal -15.
[2015-02-25 19:09:38,874: ERROR/MainProcess] Task workers.gene_annotator.annotate[7b667313-f06d-45f3-9869-6ffdb8fcce6e] raised unexpected: WorkerLostError('Worker exited prematurely: signal -15.',)
Traceback (most recent call last):
  File "/home/cycledash/cycledash/venv/lib/python2.7/site-packages/billiard/pool.py", line 1170, in mark_as_worker_lost
    human_status(exitcode)),
WorkerLostError: Worker exited prematurely: signal -15.
[2015-02-25 19:09:39,090: ERROR/MainProcess] Process 'Worker-13' pid:8388 exited with 'signal -15'
```
