### ISSUE TITLE
gene_annotator fails with "has no attribute 'db'"

### ISSUE THREAD

**Issue by arahuja** [hammerlab/cycledash#527]
Maybe this already known, but I didn't see any issue on it:

```
Traceback (most recent call last):
  File "/home/cycledash/cycledash/venv/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/cycledash/cycledash/venv/lib/python2.7/site-packages/celery/app/trace.py", line 437, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/cycledash/cycledash/workers/gene_annotator.py", line 44, in annotate
    connection, metadata, vcf_id, ensembl_release_num=75)
  File "/home/cycledash/cycledash/workers/gene_annotator.py", line 101, in get_gene_names
    str(contig), int(position))
  File "/home/cycledash/cycledash/venv/lib/python2.7/site-packages/pyensembl/ensembl_release.py", line 165, in gene_names_at_locus
    strand=strand)
  File "/home/cycledash/cycledash/venv/lib/python2.7/site-packages/pyensembl/database.py", line 226, in distinct_column_values_at_locus
    sorted=True)
  File "/home/cycledash/cycledash/venv/lib/python2.7/site-packages/pyensembl/database.py", line 150, in column_values_at_locus
    if not self.column_exists(column_name):
  File "/home/cycledash/cycledash/venv/lib/python2.7/site-packages/pyensembl/database.py", line 120, in column_exists
    return column_name in self.columns()
  File "/home/cycledash/cycledash/venv/lib/python2.7/site-packages/pyensembl/database.py", line 116, in columns
    table_info = self.connection.execute(sql).fetchall()
  File "/home/cycledash/cycledash/venv/lib/python2.7/site-packages/pyensembl/database.py", line 111, in connection
    self._connection = self._connect_or_create_database()
  File "/home/cycledash/cycledash/venv/lib/python2.7/site-packages/pyensembl/database.py", line 99, in _connect_or_create_database
    if datacache.db.db_table_exists(db, 'ensembl'):
AttributeError: 'module' object has no attribute 'db'
```

**Comment by danvk** [comment]
@iskandr @tavinathanson this looks like a pyensembl issue

**Comment by iskandr** [comment]
This looks like a mismatch between an old PyEnsembl and a newer datacache. 

Have you tried updating to 0.5.13?

**Comment by ihodes** [comment]
Fixed a while back
