### ISSUE TITLE
'module' object has no attribute 'db'

### ISSUE THREAD

**Issue by smondet** [hammerlab/cycledash#562]
Got this failure with a bunch of VCFs; the `/examine` still works for them though.

```
Traceback (most recent call last):
  File "/home/cycledash/cycledash/venv/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/cycledash/cycledash/venv/lib/python2.7/site-packages/celery/app/trace.py", line 437, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/cycledash/cycledash/workers/gene_annotator.py", line 44, in annotate
    connection, metadata, vcf_id, ensembl_release_num=75)
  File "/home/cycledash/cycledash/workers/gene_annotator.py", line 101, in get_gene_names
    str(contig), int(position))
  File "/home/cycledash/cycledash/venv/lib/python2.7/site-packages/pyensembl/ensembl_release.py", line 165, in gene_names_at_locus
    strand=strand)
  File "/home/cycledash/cycledash/venv/lib/python2.7/site-packages/pyensembl/database.py", line 226, in distinct_column_values_at_locus
    sorted=True)
  File "/home/cycledash/cycledash/venv/lib/python2.7/site-packages/pyensembl/database.py", line 150, in column_values_at_locus
    if not self.column_exists(column_name):
  File "/home/cycledash/cycledash/venv/lib/python2.7/site-packages/pyensembl/database.py", line 120, in column_exists
    return column_name in self.columns()
  File "/home/cycledash/cycledash/venv/lib/python2.7/site-packages/pyensembl/database.py", line 116, in columns
    table_info = self.connection.execute(sql).fetchall()
  File "/home/cycledash/cycledash/venv/lib/python2.7/site-packages/pyensembl/database.py", line 111, in connection
    self._connection = self._connect_or_create_database()
  File "/home/cycledash/cycledash/venv/lib/python2.7/site-packages/pyensembl/database.py", line 99, in _connect_or_create_database
    if datacache.db.db_table_exists(db, 'ensembl'):
AttributeError: 'module' object has no attribute 'db'
```

**Comment by ihodes** [comment]
Could you link to or list the run? 

This is a failure of the gene_annotator worker, looks like we have an old/new/incompatible version of datacache being used.

**Comment by smondet** [comment]
Here are some: http://hammerlab-dev3.hpc.mssm.edu/tasks/254
http://hammerlab-dev3.hpc.mssm.edu/tasks/255

**Comment by tavinathanson** [comment]
This looks like a `datacache` version mismatch, since at one point `datacache` had a `.db` and now it doesn't.

Has this been seen any time recently? If not, there's probably no longer a mismatch and we can close it. (Though open to any ideas on how to prevent this in the future.)

**Comment by Karanjkarnilesh** [comment]
plz check method name is same or not

**Comment by Karanjkarnilesh** [comment]
due to different  method name,
 this problem aries
