### ISSUE TITLE
Run 265 results in Internal Server Error

### ISSUE THREAD

**Issue by danvk** [hammerlab/cycledash#592]
http://cycledash.demeter.hpc.mssm.edu/runs/265/examine

**Comment by danvk** [comment]
It's coming from `pyvcf`:

```
2015-05-07 13:45:40,922 - cycledash - ERROR - Exception on /runs/265/examine [GET]
Traceback (most recent call last):
  File "/Users/danvk/.virtualenvs/cycledash/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/danvk/.virtualenvs/cycledash/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/danvk/.virtualenvs/cycledash/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/danvk/.virtualenvs/cycledash/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/danvk/.virtualenvs/cycledash/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/danvk/github/cycledash/cycledash/views.py", line 111, in examine
    vcf = cycledash.runs.get_vcf(run_id)
  File "/Users/danvk/github/cycledash/cycledash/runs.py", line 33, in get_vcf
    vcf['spec'] = genotypes.spec(vcf_id)
  File "/Users/danvk/.virtualenvs/cycledash/lib/python2.7/site-packages/plone/memoize/volatile.py", line 283, in replacement
    cached_value = cache[key] = fun(*args, **kwargs)
  File "/Users/danvk/github/cycledash/cycledash/genotypes.py", line 37, in spec
    return _header_spec(res['vcf_header'], res['extant_columns'])
  File "/Users/danvk/github/cycledash/cycledash/genotypes.py", line 334, in _header_spec
    reader = pyvcf.Reader(line for line in vcf_header_text.split('\n'))
  File "/Users/danvk/.virtualenvs/cycledash/lib/python2.7/site-packages/vcf/parser.py", line 288, in __init__
    self._parse_metainfo()
  File "/Users/danvk/.virtualenvs/cycledash/lib/python2.7/site-packages/vcf/parser.py", line 304, in _parse_metainfo
    line = self.reader.next()
StopIteration
```

Maybe a malformed VCF?

**Comment by ihodes** [comment]
At first glance looks okay:

[On NFS at  file:///hpc/users/hodesi01/cycledash-tmp/3passed_somatic_combined.vcf]
 
```
 ##fileformat=VCFv4.1
 ##FILTER=<ID=BCNoise,Description="Average fraction of filtered basecalls within 50 bases of the indel exceeds 0.3">
 ##FILTER=<ID=QSI_ref,Description="Normal sample is not homozygous ref or sindel Q-score < 30, ie calls with NT!=ref or QSI_NT < 30">
 ##FILTER=<ID=QSS_ref,Description="Normal sample is not homozygous ref or ssnv Q-score < 15, ie calls with NT!=ref or QSS_NT < 15">
 ##FILTER=<ID=Repeat,Description="Sequence repeat of more than 8x in the reference sequence">
 ##FILTER=<ID=SpanDel,Description="Fraction of reads crossing site with spanning deletions in either sample exceeeds 0.75">
 ##FILTER=<ID=iHpol,Description="Indel overlaps an interrupted homopolymer longer than 14x in the reference sequence">
 ##FORMAT=<ID=AU,Number=2,Type=Integer,Description="Number of 'A' alleles used in tiers 1,2">
 ##FORMAT=<ID=CU,Number=2,Type=Integer,Description="Number of 'C' alleles used in tiers 1,2">
 ##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Read depth for tier1">
 ##FORMAT=<ID=DP2,Number=1,Type=Integer,Description="Read depth for tier2">
 ##FORMAT=<ID=DP50,Number=1,Type=Float,Description="Average tier1 read depth within 50 bases">
 ##FORMAT=<ID=FDP,Number=1,Type=Integer,Description="Number of basecalls filtered from original read depth for tier1">
 ##FORMAT=<ID=FDP50,Number=1,Type=Float,Description="Average tier1 number of basecalls filtered from original read depth within 50 bases">
 ##FORMAT=<ID=GU,Number=2,Type=Integer,Description="Number of 'G' alleles used in tiers 1,2">
 ##FORMAT=<ID=SDP,Number=1,Type=Integer,Description="Number of reads with deletions spanning this site at tier1">
 ##FORMAT=<ID=SUBDP,Number=1,Type=Integer,Description="Number of reads below tier1 mapping quality threshold aligned across this site">
 ##FORMAT=<ID=SUBDP50,Number=1,Type=Float,Description="Average number of reads below tier1 mapping quality threshold aligned across sites within 50 bases">
 ##FORMAT=<ID=TAR,Number=2,Type=Integer,Description="Reads strongly supporting alternate allele for tiers 1,2">
 ##FORMAT=<ID=TIR,Number=2,Type=Integer,Description="Reads strongly supporting indel allele for tiers 1,2">
 ##FORMAT=<ID=TOR,Number=2,Type=Integer,Description="Other reads (weak support or insufficient indel breakpoint overlap) for tiers 1,2">
 ##FORMAT=<ID=TU,Number=2,Type=Integer,Description="Number of 'T' alleles used in tiers 1,2">
 ##GATKCommandLine=<ID=CombineVariants,Version=3.3-0-g37228af,Date="Sat Mar 28 20:56:49 EDT 2015",Epoch=1427590609184,CommandLineOptions="analysis_type=CombineVarian
ts input_file=[] showFullBamList=false read_buffer_size=null phone_home=AWS gatk_key=null tag=NA read_filter=[] intervals=null excludeIntervals=null interval_set_rul
e=UNION interval_merging=ALL interval_padding=0 reference_sequence=/hpc/users/mondes02/ksinai-demeter/B37-reference-genome/b37.fasta nonDeterministicRandomSeed=false
 disableDithering=false maxRuntime=-1 maxRuntimeUnits=MINUTES downsampling_type=BY_SAMPLE downsample_to_fraction=null downsample_to_coverage=1000 baq=OFF baqGapOpenP
enalty=40.0 refactor_NDN_cigar_string=false fix_misencoded_quality_scores=false allow_potentially_misencoded_quality_scores=false useOriginalQualities=false defaultB
aseQualities=-1 performanceLog=null BQSR=null quantize_quals=0 disable_indel_quals=false emit_original_quals=false preserve_qscores_less_than=6 globalQScorePrior=-1.
0 validation_strictness=SILENT remove_program_records=false keep_program_records=false sample_rename_mapping_file=null unsafe=null disable_auto_index_creation_and_lo
cking_when_reading_rods=false no_cmdline_in_header=false sites_only=false never_trim_vcf_format_field=false bcf=false bam_compression=null simplifyBAM=false disable_
bam_indexing=false generate_md5=false num_threads=1 num_cpu_threads_per_data_thread=1 num_io_threads=0 monitorThreadEfficiency=false num_bam_file_handles=null read_g
roup_black_list=null pedigree=[] pedigreeString=[] pedigreeValidationType=STRICT allow_intervals_with_unindexed_bam=false generateShadowBCF=false variant_index_type=
DYNAMIC_SEEK variant_index_parameter=-1 logging_level=INFO log_to_file=null help=false version=false variant=[(RodBindingCollection [(RodBinding name=variant source=
results/passed.somatic.snvs.vcf)]), (RodBindingCollection [(RodBinding name=variant2 source=results/passed.somatic.indels.vcf)])] out=org.broadinstitute.gatk.engine.
io.stubs.VariantContextWriterStub genotypemergeoption=UNIQUIFY filteredrecordsmergetype=KEEP_IF_ANY_UNFILTERED multipleallelesmergetype=BY_TYPE rod_priority_list=nul
l printComplexMerges=false filteredAreUncalled=false minimalVCF=false excludeNonVariants=false setKey=set assumeIdenticalSamples=false minimumN=1 suppressCommandLine
Header=false mergeInfoWithMaxAC=false filter_reads_with_N_cigar=false filter_mismatching_base_and_quals=false filter_bases_not_stored=false">
 ##INFO=<ID=AC,Number=A,Type=Integer,Description="Allele count in genotypes, for each ALT allele, in the same order as listed">
 ##INFO=<ID=AF,Number=A,Type=Float,Description="Allele Frequency, for each ALT allele, in the same order as listed">
 ##INFO=<ID=AN,Number=1,Type=Integer,Description="Total number of alleles in called genotypes">
 ##INFO=<ID=IC,Number=1,Type=Integer,Description="Number of times RU repeats in the indel allele">
 ##INFO=<ID=IHP,Number=1,Type=Integer,Description="Largest reference interrupted homopolymer length intersecting with the indel">
 ##INFO=<ID=NT,Number=1,Type=String,Description="Genotype of the normal in all data tiers, as used to classify somatic variants. One of {ref,het,hom,conflict}.">
 ##INFO=<ID=OVERLAP,Number=0,Type=Flag,Description="Somatic indel possibly overlaps a second indel.">
 ##INFO=<ID=QSI,Number=1,Type=Integer,Description="Quality score for any somatic variant, ie. for the ALT haplotype to be present at a significantly different freque
ncy in the tumor and normal">
 ##INFO=<ID=QSI_NT,Number=1,Type=Integer,Description="Quality score reflecting the joint probability of a somatic variant and NT">
 ##INFO=<ID=QSS,Number=1,Type=Integer,Description="Quality score for any somatic snv, ie. for the ALT allele to be present at a significantly different frequency in
the tumor and normal">
 ##INFO=<ID=QSS_NT,Number=1,Type=Integer,Description="Quality score reflecting the joint probability of a somatic variant and NT">
 ##INFO=<ID=RC,Number=1,Type=Integer,Description="Number of times RU repeats in the reference allele">
 ##INFO=<ID=RU,Number=1,Type=String,Description="Smallest repeating sequence unit in inserted or deleted sequence">
 ##INFO=<ID=SGT,Number=1,Type=String,Description="Most likely somatic genotype excluding normal noise states">
 ##INFO=<ID=SOMATIC,Number=0,Type=Flag,Description="Somatic mutation">
 ##INFO=<ID=SVTYPE,Number=1,Type=String,Description="Type of structural variant">
 ##INFO=<ID=TQSI,Number=1,Type=Integer,Description="Data tier used to compute QSI">
 ##INFO=<ID=TQSI_NT,Number=1,Type=Integer,Description="Data tier used to compute QSI_NT">
 ##INFO=<ID=TQSS,Number=1,Type=Integer,Description="Data tier used to compute QSS">
 ##INFO=<ID=TQSS_NT,Number=1,Type=Integer,Description="Data tier used to compute QSS_NT">
 ##INFO=<ID=set,Number=1,Type=String,Description="Source VCF for the merged record in CombineVariants">
 ##cmdline=/demeter/users/mondes02/ksinai-demeter/strelka.1.0.14/usr/libexec/consolidateResults.pl --config=/demeter/users/mondes02/ksinai-demeter/work/Seb_s_Example
/pct-13002-H039AADXX-lane-1-bwa-gap11-gep4-indelrealigned-dedup-bqsr-Strelka-exome-defaultstrelka_output/config/run.config.ini
 ##content=strelka somatic indel calls
 ##contig=<ID=1,length=249250621,assembly=b37>
 ##contig=<ID=2,length=243199373,assembly=b37>
 ##contig=<ID=3,length=198022430,assembly=b37>
 ##contig=<ID=4,length=191154276,assembly=b37>
 ##contig=<ID=5,length=180915260,assembly=b37>
 ##contig=<ID=6,length=171115067,assembly=b37>
 ##contig=<ID=7,length=159138663,assembly=b37>
 ##contig=<ID=8,length=146364022,assembly=b37>
 ##contig=<ID=9,length=141213431,assembly=b37>
 ##contig=<ID=10,length=135534747,assembly=b37>
 ##contig=<ID=11,length=135006516,assembly=b37>
 ##contig=<ID=12,length=133851895,assembly=b37>
 ##contig=<ID=13,length=115169878,assembly=b37>
 ##contig=<ID=14,length=107349540,assembly=b37>
 ##contig=<ID=15,length=102531392,assembly=b37>
 ##contig=<ID=16,length=90354753,assembly=b37>
 ##contig=<ID=17,length=81195210,assembly=b37>
 ##contig=<ID=18,length=78077248,assembly=b37>
 ##contig=<ID=19,length=59128983,assembly=b37>
 ##contig=<ID=20,length=63025520,assembly=b37>
 ##contig=<ID=21,length=48129895,assembly=b37>
 ##contig=<ID=22,length=51304566,assembly=b37>
 ##contig=<ID=X,length=155270560,assembly=b37>
 ##contig=<ID=Y,length=59373566,assembly=b37>
 ##contig=<ID=MT,length=16569,assembly=b37>
 ##contig=<ID=GL000207.1,length=4262,assembly=b37>
 ##contig=<ID=GL000226.1,length=15008,assembly=b37>
 ##contig=<ID=GL000229.1,length=19913,assembly=b37>
 ##contig=<ID=GL000231.1,length=27386,assembly=b37>
 ##contig=<ID=GL000210.1,length=27682,assembly=b37>
 ##contig=<ID=GL000239.1,length=33824,assembly=b37>
 ##contig=<ID=GL000235.1,length=34474,assembly=b37>
 ##contig=<ID=GL000201.1,length=36148,assembly=b37>
 ##contig=<ID=GL000247.1,length=36422,assembly=b37>
 ##contig=<ID=GL000245.1,length=36651,assembly=b37>
 ##contig=<ID=GL000197.1,length=37175,assembly=b37>
 ##contig=<ID=GL000203.1,length=37498,assembly=b37>
 ##contig=<ID=GL000246.1,length=38154,assembly=b37>
 ##contig=<ID=GL000249.1,length=38502,assembly=b37>
 ##contig=<ID=GL000196.1,length=38914,assembly=b37>
 ##contig=<ID=GL000248.1,length=39786,assembly=b37>
 ##contig=<ID=GL000244.1,length=39929,assembly=b37>
 ##contig=<ID=GL000238.1,length=39939,assembly=b37>
 ##contig=<ID=GL000202.1,length=40103,assembly=b37>
 ##contig=<ID=GL000234.1,length=40531,assembly=b37>
 ##contig=<ID=GL000232.1,length=40652,assembly=b37>
 ##contig=<ID=GL000206.1,length=41001,assembly=b37>
 ##contig=<ID=GL000240.1,length=41933,assembly=b37>
 ##contig=<ID=GL000236.1,length=41934,assembly=b37>
 ##contig=<ID=GL000241.1,length=42152,assembly=b37>
 ##contig=<ID=GL000243.1,length=43341,assembly=b37>
 ##contig=<ID=GL000242.1,length=43523,assembly=b37>
 ##contig=<ID=GL000230.1,length=43691,assembly=b37>
 ##contig=<ID=GL000237.1,length=45867,assembly=b37>
 ##contig=<ID=GL000233.1,length=45941,assembly=b37>
 ##contig=<ID=GL000204.1,length=81310,assembly=b37>
 ##contig=<ID=GL000198.1,length=90085,assembly=b37>
 ##contig=<ID=GL000208.1,length=92689,assembly=b37>
 ##contig=<ID=GL000191.1,length=106433,assembly=b37>
 ##contig=<ID=GL000227.1,length=128374,assembly=b37>
 ##contig=<ID=GL000228.1,length=129120,assembly=b37>
 ##contig=<ID=GL000214.1,length=137718,assembly=b37>
 ##contig=<ID=GL000221.1,length=155397,assembly=b37>
 ##contig=<ID=GL000209.1,length=159169,assembly=b37>
 ##contig=<ID=GL000218.1,length=161147,assembly=b37>
 ##contig=<ID=GL000220.1,length=161802,assembly=b37>
 ##contig=<ID=GL000213.1,length=164239,assembly=b37>
 ##contig=<ID=GL000211.1,length=166566,assembly=b37>
 ##contig=<ID=GL000199.1,length=169874,assembly=b37>
 ##contig=<ID=GL000217.1,length=172149,assembly=b37>
 ##contig=<ID=GL000216.1,length=172294,assembly=b37>
 ##contig=<ID=GL000215.1,length=172545,assembly=b37>
 ##contig=<ID=GL000205.1,length=174588,assembly=b37>
 ##contig=<ID=GL000219.1,length=179198,assembly=b37>
 ##contig=<ID=GL000224.1,length=179693,assembly=b37>
 ##contig=<ID=GL000223.1,length=180455,assembly=b37>
 ##contig=<ID=GL000195.1,length=182896,assembly=b37>
 ##contig=<ID=GL000212.1,length=186858,assembly=b37>
 ##contig=<ID=GL000222.1,length=186861,assembly=b37>
 ##contig=<ID=GL000200.1,length=187035,assembly=b37>
 ##contig=<ID=GL000193.1,length=189789,assembly=b37>
 ##contig=<ID=GL000194.1,length=191469,assembly=b37>
 ##contig=<ID=GL000225.1,length=211173,assembly=b37>
 ##contig=<ID=GL000192.1,length=547496,assembly=b37>
 ##fileDate=20150328
 ##germlineIndelTheta=0.0001
 ##germlineSnvTheta=0.001
 ##priorSomaticIndelRate=1e-06
 ##priorSomaticSnvRate=1e-06
 ##reference=file:///hpc/users/mondes02/ksinai-demeter/B37-reference-genome/b37.fasta
 ##source=strelka
 ##source_version=2.0.17.strelka1
 ##startTime=Sat Mar 28 20:53:08 2015
 #CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  NORMAL.variant  NORMAL.variant2 TUMOR.variant   TUMOR.variant2
```

**Comment by ihodes** [comment]
Hah, I was looking at the wrong VCF: the actual VCF appears to have no header, which Cycledash needs to send metadata to the client. 

This is filed at https://github.com/hammerlab/cycledash/issues/490
