### ISSUE TITLE
internal server error creating new run

### ISSUE THREAD

**Issue by timodonnell** [hammerlab/cycledash#746]
Sorry this error isn't more informative. In our hammerlab cycledash instance, when I try to Add a Run with these files, I get an "internal server error":

/user/ahujaa01/brody-lymphoma/brody_442/brody_442-bcell-tumor-bwa-mem-gap11-gep4-dedup-indelrealigned-bqsr.bam

/user/ahujaa01/brody-lymphoma/brody_442/brody_442-tcell-normal-bwa-mem-gap11-gep4-dedup-indelrealigned-bqsr.bam

/user/ahujaa01/brody-lymphoma/brody_442/brody_442-bcell-bwa-mem-gap11-gep4-dedup-indelrealigned-bqsr-Mutect-default-merged.vcf

This happened recently (around 1:40 EST); perhaps there's a record in the logs.

![](https://files.slack.com/files-pri/T02781A0K-F06FCRU80/pasted_image_at_2015_06_17_01_26_pm.png)

**Comment by danvk** [comment]
Here's what I see in the logs:

```
2015-06-17 13:45:13,846 - cycledash - ERROR - Internal Error
Traceback (most recent call last):
  File "/home/cycledash/cycledash/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/cycledash/cycledash/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/cycledash/cycledash/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 446, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/cycledash/cycledash/venv/lib/python2.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/cycledash/cycledash/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 550, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/cycledash/cycledash/cycledash/helpers.py", line 201, in wrapper
    return f(*args, **kwargs)
  File "/home/cycledash/cycledash/cycledash/helpers.py", line 173, in wrapper
    resp = marshalled(*args, **kwargs)
  File "/home/cycledash/cycledash/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 642, in wrapper
    resp = f(*args, **kwargs)
  File "/home/cycledash/cycledash/cycledash/runs.py", line 71, in post
    request.validated_body).returning(*runs.c).execute().fetchone()
  File "/home/cycledash/cycledash/venv/lib/python2.7/site-packages/sqlalchemy/sql/base.py", line 386, in execute
    return e._execute_clauseelement(self, multiparams, params)
  File "/home/cycledash/cycledash/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/cycledash/cycledash/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/home/cycledash/cycledash/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1339, in _handle_dbapi_exception
    exc_info
  File "/home/cycledash/cycledash/venv/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/home/cycledash/cycledash/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/home/cycledash/cycledash/venv/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 442, in do_execute
    cursor.execute(statement, parameters)
IntegrityError: (psycopg2.IntegrityError) duplicate key value violates unique constraint "vcfs_uri_key"
DETAIL:  Key (uri)=(/user/ahujaa01/brody-lymphoma/brody_442/brody_442-bcell-bwa-mem-gap11-gep4-dedup-indelrealigned-bqsr-Mutect-default-merged.vcf) already exists.
 [SQL: 'INSERT INTO vcfs (caller_name, notes, uri, tumor_bam_id, normal_bam_id, project_id) VALUES (%(caller_name)s, %(notes)s, %(uri)s, %(tumor_bam_id)s, %(normal_bam_id)s, %(project_id)s) RETURNING vcfs.id, vcfs.created_at, vcfs.caller_name, vcfs.validation_vcf, vcfs.notes, vcfs.uri, vcfs.vcf_header, vcfs.extant_columns, vcfs.precision, vcfs.recall, vcfs.f1score, vcfs.genotype_count, vcfs.tumor_bam_id, vcfs.normal_bam_id, vcfs.project_id, vcfs.normal'] [parameters: {'notes': u'442 mutect', 'tumor_bam_id': 124L, 'uri': u'/user/ahujaa01/brody-lymphoma/brody_442/brody_442-bcell-bwa-mem-gap11-gep4-dedup-indelrealigned-bqsr-Mutect-default-merged.vcf', 'caller_name': u'Mutect2', 'normal_bam_id': 123L, 'project_id': 24L}]
```
