### ISSUE TITLE
The indexer is having permission issues

### ISSUE THREAD

**Issue by jaclynperrone** [hammerlab/cycledash#796]
when I try to upload this BAM file:
/datasets/martignetti_ovarian/189/Illumina_DNA/PT189_Normal_Exome/Processed/NGS.2_7_2b.WES/results/PT189_Normal_Exome.PT189_Normal_Exome.clean.dedup.recal.bam

`[2015-07-23 12:44:50,816: ERROR/MainProcess] Task workers.indexer.index[05b77263-2324-4c22-a5ee-e6c3fe52d98e] raised unexpected: PyWebHdfsException('{"RemoteException":{"message":"Permission denied: user=username, access=WRITE, inode=\\"\\/\\":hdfs:supergroup:drwxr-xr-x","exception":"AccessControlException","javaClassName":"org.apache.hadoop.security.AccessControlException"}}\n',)
Traceback (most recent call last):
  File "/Users/jaclynperrone/Workspace/cycledash/venv/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/Users/jaclynperrone/Workspace/cycledash/venv/lib/python2.7/site-packages/celery/app/trace.py", line 437, in __protected_call__
    return self.run(*args, **kwargs)
  File "/Users/jaclynperrone/Workspace/cycledash/workers/indexer.py", line 38, in index
    put_new_file_to_hdfs(bai_json_path, index_json_str)
  File "/Users/jaclynperrone/Workspace/cycledash/workers/shared.py", line 77, in put_new_file_to_hdfs
    _get_hdfs_client().create_file(hdfs_path, contents)
  File "/Users/jaclynperrone/Workspace/cycledash/venv/lib/python2.7/site-packages/pywebhdfs/webhdfs.py", line 92, in create_file
    _raise_pywebhdfs_exception(response.status_code, response.content)
  File "/Users/jaclynperrone/Workspace/cycledash/venv/lib/python2.7/site-packages/pywebhdfs/webhdfs.py", line 436, in _raise_pywebhdfs_exception
    raise errors.PyWebHdfsException(msg=message)
PyWebHdfsException: {"RemoteException":{"message":"Permission denied: user=username, access=WRITE, inode=\"\/\":hdfs:supergroup:drwxr-xr-x","exception":"AccessControlException","javaClassName":"org.apache.hadoop.security.AccessControlException"}}`

**Comment by ihodes** [comment]
This may be because hdfs httpfs is down—unclear.
