### ISSUE TITLE
Unable to submit VCF with Structural Variants

### ISSUE THREAD

**Issue by danvk** [hammerlab/cycledash#840]
I tried to submit [this VCF][1] which was produced by Manta. The genotype_extractor failed with this error:

```
Traceback (most recent call last):
  File "/home/cycledash/cycledash/venv/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/cycledash/cycledash/venv/lib/python2.7/site-packages/celery/app/trace.py", line 437, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/cycledash/cycledash/workers/genotype_extractor.py", line 25, in extract
    return _extract(vcf_id)
  File "/home/cycledash/cycledash/workers/genotype_extractor.py", line 43, in _extract
    reader, header_text, release = load_vcf(vcf['uri'])
  File "/home/cycledash/cycledash/workers/shared.py", line 112, in load_vcf
    release = guess_ensembl_release(filepath)
  File "/home/cycledash/cycledash/workers/shared.py", line 96, in guess_ensembl_release
    return release
UnboundLocalError: local variable 'release' referenced before assignment
```

[1]: https://gist.github.com/danvk/1b909a87b0cac5e758b5

**Comment by danvk** [comment]
Thanks for fixing this, @armish !
